### ISSUE TITLE
It's turn off the TV but I can't turn it on ?

### ISSUE THREAD

**Issue by daniel4099** [mmende/homebridge-samsungtv-control#11]
Hi Guys, great app.

But all I can do is turn off the tv, i can't turn it off.
What should I do ?

**Comment by mmende** [comment]
Hi,
As mentioned in the limitations section of the readme turning on most of the samsung tv's will not work through this plugin since the remote control protocol used here works over network and when turned off the tv disconnects from the network and is therefore not reachable anymore.

Kind regards
