### ISSUE TITLE
Whitch App

### ISSUE THREAD

**Issue by EpicNeo** [mmende/homebridge-samsungtv-control#2]
With witch app can i make scenes to set channel? I tried several eg. the Eve app, HomeDash, myHome and Hesperus. With non of these it is possible. Non have implement these characteristics to set scenes with.

**Comment by mmende** [comment]
There is a sample app from Apple called [HomeKit Catalog](https://developer.apple.com/library/ios/samplecode/HomeKitCatalog/Introduction/Intro.html) that has to be compiled on your device since it's not in the App Store. There is also a section in the [homebridge readme](https://github.com/nfarina/homebridge#adding-homebridge-to-ios) with more infos.

**Comment by EpicNeo** [comment]
Ok, thank you for the info.

**Comment by mmende** [comment]
You're welcome.
