### ISSUE TITLE
Is there a way to turn the tv off via ethernet?

### ISSUE THREAD

**Issue by socialsti** [mmende/homebridge-samsungtv-control#3]
Would it be possible to turn the tv on via ethernet?

**Comment by mmende** [comment]
Hi,
turning the tv off should work, turning it back on from standby unfortunately doesn't work for most devices since they close all network interfaces when going into standby.

It looks like samsung recently changed their network remote control protocol a bit so that the tv requires a keycode authentication before allowing to control it. Unfortunately this is not implemented in the remote control module yet. So if you have a newer tv chances are high that the module can not control your tv at all. I will further investigate on this and will update the readme with this details soon.
