### ISSUE TITLE
What commands to say

### ISSUE THREAD

**Issue by Irish-link** [mmende/homebridge-samsungtv-control#4]
I saw the section about usage however i am still confused as to what commands i can say. When i try anything it says "sorry that is not supported"

Turn the tv off works just fine but can you give me an example of any other command i could try.

**Comment by mmende** [comment]
Hi,
If you have installed the [HomeKit Catalog app](https://developer.apple.com/library/ios/samplecode/HomeKitCatalog/Introduction/Intro.html) you can specify scenes where you set the channel characteristic to a specific channel number or the volume characteristic to increase, decrease or mute the tv. The scenes name is than a phrase siri will understand. Just note that siri only recognizes the exact wording you've chosen for your scene. Your could e.g. create a scene "I would like to watch Channel 4" and set the channel characteristic (second one after on/off toggle) to 4. If you are using iOS 10 I still suggest using the HomeKit Catalog app since the included Home app seems not to allow changing other characteristics beside the on/off one.
