### ISSUE TITLE
How do i use this

### ISSUE THREAD

**Issue by zucram** [mmende/homebridge-samsungtv-control#6]
I have a working homebridge configuration and i would like to control my samsung tv (mainly switching inputs) using the appel tv siri remote. Do i just need to add this extension and the config file? Where do i add the input switching? If someone has some working code or config file please add this so that i can take a look and modify it so it works. My TV is a 2014 H-series samsung tv.

**Comment by mmende** [comment]
Unfortunately the newer tizen tv's as yours don't work with this plugin yet because the old remote control protocol does not exist any more on them. I am working on a newer version with support for these newer tv's but since the samsung documentation for this topic just does not exist I have to reverse engineer their own app or some working third party apps to support the newer tv's. (I'm stuck at the authentication process at the moment...) 

Even if the plugin would support your tv right now I suspect that changing the tv's input channel with the siri remote would probable not work as expected since the 4th gen apple tv automatically changes the input channel via HDMI-CEC back to it's own input source when something happens on the remote. But that's just a guess. I will check this with my old samsung tv and the new apple tv in the next days even though you'll have to wait for the new plugin version.

Kind regards

**Comment by zucram** [comment]
Hi! 
I wasn't aware that 2014 tv's was tizen? I thought that started 2015. 
I do however think that the use case could work. From my experience HDMI-CEC switches when something happens as you say but whenever i start my playstation4 the TV switches over to that and then if i touch the remote it switches back to apple tv. And then back and forward as i please. So hopefully a plugin like this could switch over to the other input and then stay there if i don't touch the apple remote. Worth a try anyways if we can get the plugin to work. 

/Marcus

**Comment by jat80** [comment]
I have a late 2012 samsung smart TV that I would like to change volume.  What should the config.json file look like for volume details or will it just work as it is? @mmende @zucram

**Comment by mmende** [comment]
You don't need any special configuration stuff for the volume. However to adjust the volume and channel characteristics you must set up scenes for those with an app other than the native iOS Home app like e.g. the homekit catalog app. You can find a more detailed description on how to install this example app and why these characteristics are special in this issue #9.

Kind regards

**Comment by mmende** [comment]
The plugin has been reimplemented completely and can be found [here](https://github.com/mmende/homebridge-samsungtv-control2) now. I am closing all issues in this repository therefore. Please consider testing the new plugin and help me improve it.
